battleship.game.api.statistics:
  path:     /statistics/page/{page}
  defaults: { _controller: GameBundle:Statistics:overall}
  methods:  [GET]
  requirements:
    page: \d+
battleship.game.api.init:
  path:     game/init
  defaults: { _controller: GameBundle:Game:init }
  methods:  [POST]
  requirements:
    _format: json
battleship.game.api.turn:
  path:     game/turn
  defaults: { _controller: GameBundle:Game:turn }
  methods:  [PATCH]
  requirements:
    _format: json
