language: "php"

php:
    - "7.0"

env:
  - DATABASE_ENGINE=pdo_mysql DATABASE_PORT=3306
  - DATABASE_ENGINE=pdo_pgsql DATABASE_PORT=5432 DATABASE_USER=postgres

services:
    - "mysql"
    - "pgsql"

before_script:
    - "cp app/config/parameters.yml.dist app/config/parameters.yml"
    - "composer install --no-progress --no-interaction"

script:
    - "php bin/phpunit -c phpunit.xml --colors=always --verbose --coverage-clover=coverage.xml"

after_success:
    - "bash <(curl -s https://codecov.io/bash)"
