imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    battleship_game.setting.game_size.min: 7
    battleship_game.setting.game_size.max: 12
    battleship_game.setting.opponents_count.min: 1 # Multiplayer in WIP!
    battleship_game.setting.opponents_count.max: 1 # Multiplayer in WIP!
    battleship_game.setting.limits.per_page.game_results: 5

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  "%database_encoding%"
        path:     "%database_path%"
        server_version: 5
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

framework:
   # esi:             ~
   # translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
   # validation:      { enable_annotations: true }
   # serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        # assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name:        "battleship-game-api"
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# left for example purposes
#jms_serializer:
#    handlers:
#        datetime:
#            default_format: "c" # ISO8601
#            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set
#
#    property_naming:
#        separator:  _
#        lower_case: true
#
#    metadata:
#        cache: file
#        debug: "%kernel.debug%"
#        file_cache:
#            dir: "%kernel.cache_dir%/serializer"
#
#        # Using auto-detection, the mapping files for each bundle will be expected in the Resources/config/serializer directory.
#        #
#        # example:
#        #      class: EM\GameBundle\Entity\Game
#        # expected path: @GameBundle/Resources/config/serializer/Entity.Game.(yml|xml|php)
#        auto_detection: false
#
#        # if you don't want to use auto-detection, you can also define the namespace prefix and the corresponding directory explicitly
#        directories:
#            game-bundle-entity:
#                namespace_prefix: "EM\\GameBundle\\Entity\\"
#                path: "@GameBundle/Resources/config/serializer/entity"
